"""FixedBlue3v3MAPPOTrainer – shared red actor, team critic, fixed-rule blue (auto-generated by workers)."""
from __future__ import annotations

import time
from copy import deepcopy
from pathlib import Path
from typing import Any

import numpy as np
import torch
from torch import nn

from ..environment_3v3 import GS_DIM, OBS_DIM, Homogeneous3v3AirCombatEnv
from ..scenario_3v3 import RED_IDS
from .buffer_3v3 import MAPPOBuffer3v3
from .networks import CentralizedCritic, GaussianActor
from .vector_env_3v3 import make_combat_vector_env_3v3

CHECKPOINT_VERSION_3V3 = 1
CHECKPOINT_FAMILY = "homogeneous_3v3_fixed_blue"


def resolve_device(requested: str) -> torch.device:
    if requested == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    device = torch.device(requested)
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA was requested but is not available")
    return device


class FixedBlue3v3MAPPOTrainer:
    """Red shared-actor MAPPO vs fixed-rule nearest-pursuit blue."""

    def __init__(self, env_config: str | Path, config: dict[str, Any]) -> None:
        self.env_config = str(env_config)
        self.config = deepcopy(config)
        t, n, e = self.config["training"], self.config["network"], self.config["experiment"]
        if t.get("training_mode") != "fixed_rule_blue_3v3":
            raise ValueError("training_mode must be fixed_rule_blue_3v3")

        self.device = resolve_device(e["device"])
        torch.manual_seed(e["seed"])
        self.num_envs = int(t["num_envs"])
        self.num_env_workers = int(t.get("num_env_workers", 4))
        self.rollout_steps = int(t["rollout_steps"])
        self.total_env_steps = int(t["total_env_steps"])

        # Shared red actor + team critic
        self.red_actor = GaussianActor(OBS_DIM, 3, n["hidden_dim"], n["log_std_init"]).to(self.device)
        self.team_critic = CentralizedCritic(GS_DIM, n["hidden_dim"]).to(self.device)
        lr = t["learning_rate"]
        self.actor_optimizer = torch.optim.Adam(self.red_actor.parameters(), lr=lr)
        self.critic_optimizer = torch.optim.Adam(self.team_critic.parameters(), lr=lr)

        # Vector env (workers auto-generate blue actions internally)
        self.vector_env = make_combat_vector_env_3v3(self.env_config, self.num_envs, self.num_env_workers)
        self.buffer = MAPPOBuffer3v3(self.rollout_steps, self.num_envs)

        self.rng = np.random.default_rng(e["seed"])
        self.env_steps = 0
        self.update_count = 0

        # Current state arrays
        self.current_observations = np.empty((self.num_envs, 6, OBS_DIM), dtype=np.float32)
        self.current_global_states = np.empty((self.num_envs, GS_DIM), dtype=np.float32)
        self.current_alive_masks = np.empty((self.num_envs, 6), dtype=np.float32)
        self.episode_returns = np.zeros(self.num_envs, dtype=np.float64)
        self.episode_lengths = np.zeros(self.num_envs, dtype=np.int32)

        self.best_score: tuple[float, ...] | None = None
        self._timing: dict[str, float] = {"env_step": 0.0, "policy_inference": 0.0, "ppo_update": 0.0, "reset": 0.0}

        self.reset_environments()

    # -----------------------------------------------------------------
    def reset_environments(self) -> None:
        specs = [{"seed": int(self.rng.integers(0, 2**31 - 1))} for _ in range(self.num_envs)]
        obs, gs, am = self.vector_env.reset(specs)
        self.current_observations = obs
        self.current_global_states = gs
        self.current_alive_masks = am
        self.episode_returns.fill(0)
        self.episode_lengths.fill(0)

    # -----------------------------------------------------------------
    def collect_rollout(self, remaining: int | None = None) -> list[dict[str, Any]]:
        steps = self.rollout_steps if remaining is None else min(self.rollout_steps, remaining // self.num_envs)
        if steps <= 0:
            raise ValueError("remaining must contain one full vector step")
        if self.buffer.rollout_steps != steps:
            self.buffer = MAPPOBuffer3v3(steps, self.num_envs)
        self.buffer.clear()
        completed: list[dict[str, Any]] = []
        N = self.num_envs

        for _ in range(steps):
            t0 = time.perf_counter()
            red_obs = self.current_observations[:, :3, :]  # [N, 3, 68]
            red_obs_flat = red_obs.reshape(-1, OBS_DIM)  # [N*3, 68]
            red_alive_mask = self.current_alive_masks[:, :3]  # [N, 3]

            with torch.no_grad():
                all_actions, all_log_probs = self.red_actor.sample_action(
                    torch.as_tensor(red_obs_flat, device=self.device))
                team_values = self.team_critic(
                    torch.as_tensor(self.current_global_states, device=self.device))
            red_actions = all_actions.cpu().numpy().reshape(N, 3, 3)
            red_log_probs = all_log_probs.cpu().numpy().reshape(N, 3)
            t1 = time.perf_counter()
            self._timing["policy_inference"] += t1 - t0

            # Step: only send red actions; workers compute blue actions
            t2 = time.perf_counter()
            (next_obs, next_gs, team_rewards, terminated, truncated,
             alive_masks, _atg, _dc, _tac,
             _atk_r, _atk_b, _bdy_r, _bdy_b, _col_r, _col_b,
             _red_succ, _blue_succ, _geom, _cd, _rc, _oc) = self.vector_env.step(red_actions)
            t3 = time.perf_counter()
            self._timing["env_step"] += t3 - t2

            self.episode_returns += team_rewards
            self.episode_lengths += 1

            # Handle done envs
            done_mask = terminated | truncated
            done_indices = np.where(done_mask)[0]
            if len(done_indices) > 0:
                t_reset = time.perf_counter()
                sorted_done = np.sort(done_indices)
                for idx in sorted_done:
                    completed.append({
                        "returns": float(self.episode_returns[idx]),
                        "length": int(self.episode_lengths[idx]),
                    })
                    self.episode_returns[idx] = 0.0
                    self.episode_lengths[idx] = 0
                reset_specs = [{"seed": int(self.rng.integers(0, 2**31 - 1))} for _ in sorted_done]
                new_obs, new_gs, new_am = self.vector_env.reset_at(sorted_done, reset_specs)
                next_obs[sorted_done] = new_obs
                next_gs[sorted_done] = new_gs
                alive_masks[sorted_done] = new_am
                self._timing["reset"] += time.perf_counter() - t_reset

            self.buffer.add(
                red_obs,
                self.current_global_states.copy(),
                red_actions, red_log_probs,
                red_alive_mask, team_rewards,
                team_values.cpu().numpy(), done_mask,
            )

            self.current_observations = next_obs
            self.current_global_states = next_gs
            self.current_alive_masks = alive_masks
            self.env_steps += N

        # Final bootstrap
        with torch.no_grad():
            last_values = self.team_critic(
                torch.as_tensor(self.current_global_states, device=self.device)).cpu().numpy()
        t_cfg = self.config["training"]
        self.buffer.compute_returns_and_advantages(last_values, t_cfg["gamma"], t_cfg["gae_lambda"])
        return completed

    # -----------------------------------------------------------------
    def update(self) -> dict[str, Any]:
        t0 = time.perf_counter()
        t_cfg = self.config["training"]

        # Actor update
        obs_flat = torch.as_tensor(self.buffer.observations.reshape(-1, OBS_DIM), device=self.device)
        actions_flat = torch.as_tensor(self.buffer.actions.reshape(-1, 3), device=self.device)
        old_lp_flat = torch.as_tensor(self.buffer.log_probs.reshape(-1), device=self.device)

        advantages_team = torch.as_tensor(self.buffer.advantages.reshape(-1, 1), device=self.device)
        advantages = advantages_team.expand(-1, 3).reshape(-1)
        advantages = (advantages - advantages.mean()) / (advantages.std(unbiased=False) + 1e-8)

        alive_mask = torch.as_tensor(self.buffer.agent_alive_masks.reshape(-1), device=self.device)

        actor_data = []
        for _ in range(t_cfg["ppo_epochs"]):
            order = self.rng.permutation(len(obs_flat))
            for start in range(0, len(obs_flat), t_cfg["minibatch_size"]):
                idx = torch.as_tensor(order[start:start + t_cfg["minibatch_size"]], device=self.device)
                idx_alive = idx[alive_mask[idx] > 0.5]
                if len(idx_alive) == 0:
                    continue
                new_lp, entropy = self.red_actor.evaluate_actions(obs_flat[idx_alive], actions_flat[idx_alive])
                log_ratio = new_lp - old_lp_flat[idx_alive]
                ratio = log_ratio.exp()
                adv = advantages[idx_alive]
                policy_loss = -torch.minimum(
                    ratio * adv,
                    ratio.clamp(1 - t_cfg["clip_coef"], 1 + t_cfg["clip_coef"]) * adv,
                ).mean()
                loss = policy_loss - t_cfg["entropy_coef"] * entropy.mean()
                self.actor_optimizer.zero_grad()
                loss.backward()
                grad = nn.utils.clip_grad_norm_(self.red_actor.parameters(), t_cfg["max_grad_norm"])
                self.actor_optimizer.step()
                actor_data.append((policy_loss.item(), entropy.mean().item(), float(grad)))

        # Critic update
        states = torch.as_tensor(self.buffer.global_states.reshape(-1, GS_DIM), device=self.device)
        returns = torch.as_tensor(self.buffer.returns.reshape(-1), device=self.device)
        critic_losses = []
        for _ in range(t_cfg["ppo_epochs"]):
            order = self.rng.permutation(len(states))
            for start in range(0, len(states), t_cfg["minibatch_size"]):
                idx = torch.as_tensor(order[start:start + t_cfg["minibatch_size"]], device=self.device)
                v_loss = ((self.team_critic(states[idx]) - returns[idx]) ** 2).mean()
                loss = t_cfg["value_loss_coef"] * v_loss
                self.critic_optimizer.zero_grad()
                loss.backward()
                nn.utils.clip_grad_norm_(self.team_critic.parameters(), t_cfg["max_grad_norm"])
                self.critic_optimizer.step()
                critic_losses.append(v_loss.item())

        self.update_count += 1
        self._timing["ppo_update"] += time.perf_counter() - t0

        v = np.asarray(actor_data) if actor_data else np.zeros((0, 3))
        cl = np.asarray(critic_losses) if critic_losses else np.zeros(0)
        return {
            "policy_loss": float(v[:, 0].mean()) if len(v) else 0.0,
            "entropy": float(v[:, 1].mean()) if len(v) else 0.0,
            "actor_grad_norm": float(v[:, 2].mean()) if len(v) else 0.0,
            "value_loss": float(cl.mean()) if len(cl) else 0.0,
            "advantage_mean": float(advantages.mean()),
            "advantage_std": float(advantages.std(unbiased=False)),
        }

    # -----------------------------------------------------------------
    def training_signature(self) -> dict[str, Any]:
        t_cfg = self.config["training"]
        sig_cfg = deepcopy(self.config)
        sig_cfg["training"].pop("total_env_steps", None)
        sig_cfg["training"].pop("num_env_workers", None)
        sig_cfg["experiment"].pop("device", None)
        sig_cfg["experiment"].pop("output_dir", None)
        return {
            "checkpoint_family": CHECKPOINT_FAMILY,
            "checkpoint_version": CHECKPOINT_VERSION_3V3,
            "observation_dim": OBS_DIM,
            "global_state_dim": GS_DIM,
            "team_size": 3,
            "network": deepcopy(self.config["network"]),
            "ppo": {k: t_cfg[k] for k in ("learning_rate", "gamma", "gae_lambda", "clip_coef", "entropy_coef", "value_loss_coef", "max_grad_norm", "ppo_epochs", "minibatch_size")},
            "num_envs": self.num_envs,
            "rollout_steps": self.rollout_steps,
            "config": sig_cfg,
        }

    # -----------------------------------------------------------------
    def save_checkpoint(self, path: str | Path) -> None:
        path = Path(path); path.parent.mkdir(parents=True, exist_ok=True)
        data: dict[str, Any] = {
            "checkpoint_family": CHECKPOINT_FAMILY, "checkpoint_version": CHECKPOINT_VERSION_3V3,
            "config": self.config, "training_signature": self.training_signature(),
            "env_steps": self.env_steps, "update_count": self.update_count,
            "shared_red_actor": self.red_actor.state_dict(),
            "centralized_team_critic": self.team_critic.state_dict(),
            "actor_optimizer": self.actor_optimizer.state_dict(),
            "critic_optimizer": self.critic_optimizer.state_dict(),
            "best_score": self.best_score,
            "num_env_workers": self.num_env_workers,
            "numpy_rng_state": self.rng.bit_generator.state,
            "torch_cpu_rng_state": torch.get_rng_state(),
            "torch_cuda_rng_state": torch.cuda.get_rng_state_all() if torch.cuda.is_available() else None,
        }
        torch.save(data, path)

    def load_checkpoint(self, path: str | Path) -> None:
        ckpt = torch.load(path, map_location="cpu", weights_only=False)
        if ckpt.get("checkpoint_family") != CHECKPOINT_FAMILY:
            raise RuntimeError(
                f"Expected checkpoint family '{CHECKPOINT_FAMILY}', got '{ckpt.get('checkpoint_family')}'. "
                "1v1 v6 checkpoints are incompatible with 3v3 (different observation dims, training semantics).")
        self.red_actor.load_state_dict(ckpt["shared_red_actor"])
        self.team_critic.load_state_dict(ckpt["centralized_team_critic"])
        self.actor_optimizer.load_state_dict(ckpt["actor_optimizer"])
        self.critic_optimizer.load_state_dict(ckpt["critic_optimizer"])
        self.env_steps = int(ckpt["env_steps"])
        self.update_count = int(ckpt["update_count"])
        self.best_score = ckpt.get("best_score")
        self.rng.bit_generator.state = ckpt["numpy_rng_state"]
        torch.set_rng_state(ckpt["torch_cpu_rng_state"])
        if torch.cuda.is_available() and ckpt.get("torch_cuda_rng_state") is not None:
            torch.cuda.set_rng_state_all(ckpt["torch_cuda_rng_state"])
        self.reset_environments()

    def close(self) -> None:
        self.vector_env.close()
